import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import LenisScroller from "@/components/LenisScroller";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Nav/Navbar";
import Footer from "./(home)/footer";

const dmSans = DM_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LenisScroller>
     

      <body className={`${dmSans.variable} antialiased`}>
      <ThemeProvider
          attribute="class" // Povie next-themes, aby menil triedu na <html> elemente
          defaultTheme="system" // Predvolene použi systémové nastavenie
          enableSystem // Povolí detekciu systémového nastavenia
          disableTransitionOnChange // Voliteľné: Vypne prechody počas prepínania témy pre hladší zážitok
        >
          <Navbar/>
          {children}
          <Footer/>
          <Toaster/>
        </ThemeProvider>
      </body>
      </LenisScroller>
    </html>
  );
}
